openapi: 3.0.0
info:
  title: Social App
  description: Social App API
  version: 1.0.1

servers:
  - url: http://localhost:3003/api/v1
    description: Development server for login via Insta, fb, Linkedin
  - url: https://localhost:3003/api/v1
    description: Dummy server for testing

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
      bearerFormat: JWT
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /insta:
    get:
      summary: Get insta user data
      responses:
        "200": #status code
          description: Success and return insta user data
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: string
                  following:
                    type: string
                  posts:
                    type: string
                  likes:
                    type: string
